<map version="1.0.1">
<node TEXT="BP STEPS">
<node TEXT="循环或条件判断">
<node TEXT="IF, ELSE IF, ELSE">
<node TEXT="条件判断后执行相关命令"></node></node>
<node TEXT="LOOP">
<node TEXT="按次数循环"></node>
<node TEXT="按持续时间循环"></node>
<node TEXT="按列表循环"></node>
<node TEXT="按文件的行循环"></node></node>
<node TEXT="WHILE">
<node TEXT="条件判断为 True 时执行相关命令"></node></node></node>
<node TEXT="子程序（函数）">
<node TEXT="DEFINE">
<node TEXT="定义一个子程序（函数）"></node></node>
<node TEXT="CALL">
<node TEXT="调用子程序（函数）"></node></node></node>
<node TEXT="容器">
<node TEXT="GROUP">
<node TEXT="steps 的容器，可设定是否执行"></node></node></node>
<node TEXT="退出">
<node TEXT="RETRURN">
<node TEXT="退出 DEIFINE 或主程序"></node></node>
<node TEXT="BREAK">
<node TEXT="退出 LOOP 或 WHILE"></node></node></node>
</node></map>
